### PR TITLE
Use an available version of openlayers

### PR DESCRIPTION
**Pull request by thocou**
URL are the ones described in the OpenLayers quick start: https://openlayers.org/en/latest/doc/quickstart.html

### CODE REVIEW

**Comment by thocou** [comment]
> But why do we not install CSS and JS locally in the first place?

Yes, that's an option too. 
i wanted to keep the imports as external reference because there were so.
But they can be easily attached if you prefer.

**Comment by thocou** [comment]
JS and CSS have been attached to the repository.

**Comment by thocou** [comment]
Note: this merge-request fixes the display of the maps which are currently not loading, both on `/location/evening/` and `/location/conference/`.

**Comment by drwetter** [comment]
@thocou I hope I didn't cause any trouble. I can't merge this, Björn in charge here.

**Pull request merged**
